### ISSUE TITLE
Re-release openrtm_aist_core 1.1.0

### ISSUE THREAD

**Issue by k-okada** [start-jsk/openrtm_aist_core#20]
please relase current version, this may fixed rtm-config/openrtm-aist.pc, please keep package version to 1.1.0, which we want sync with original verison

**Comment by 130s** [comment]
I opened [a discussion](https://code.google.com/p/rtm-ros-robotics/issues/detail?id=165#c13) about more intuitive way of versioning both compliant upstream package and rtm-ros package. Once it gets settled I'm happy to work on this.

**Comment by 130s** [comment]
Done http://code.google.com/p/rtm-ros-robotics/issues/detail?id=165#c20

**Comment by 130s** [comment]
Reopening due to the glitch #23

**Comment by 130s** [comment]
Ouch I made a mistake in the last release process (forgot to remove and re-create `tag` in devel repo). Need to roll back some things.

**Comment by 130s** [comment]
Hooray now finally got back to normal build status. http://jenkins.ros.org/job/ros-groovy-openrtm-aist_binarydeb_precise_amd64/35/
