### ISSUE TITLE
Add unit test to travis to examine pull request by travis

### ISSUE THREAD

**Issue by 130s** [start-jsk/openrtm_aist_core#47]
I'm not sure if [test_openrtm_aist.test](https://github.com/start-jsk/openrtm_aist_core/blob/master/openrtm_aist/test/test_openrtm_aist.test) is complete, but does it make sense to add it to travis?

**Comment by 130s** [comment]
I think `rostest` is already added (like [here](https://github.com/start-jsk/openrtm_aist_core/commit/3c244525df71876f1e293697fa6144757bf6bb68#diff-354f30a63fb0907d4ad57269548329e3)). Closing.

Now the question is if the test file `test_openrtm_aist.test` is sufficient or not though.

**Comment by k-okada** [comment]
note: 
In the travis, we tested for both 'devel' and 'install', 
1) as for devel/src directory, all 'add_rostest()' (
https://github.com/start-jsk/openrtm_aist_core/blob/master/openrtm_aist/catkin.cmake#L96) is tested in the travis 
https://github.com/start-jsk/openrtm_aist_core/blob/master/.travis.yml#L65,
2) after 'catkin_make install', travis removes devel and `src` directory and tested again(https://github.com/start-jsk/openrtm_aist_core/blob/master/.travis.yml#L70), at this time we only tested the file that has '.test' in the suffix. see http://answers.ros.org/question/131646/how-do-i-test-code-agenst-catkin-install-ed-directory/ for discussion.
