### ISSUE TITLE
Release 1.1.0-7

### ISSUE THREAD

**Issue by 130s** [start-jsk/openrtm_aist_core#49]
Pre-release test using the artifact from Release Repository [was aborted for unknown reason](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openrtm_aist_core/2/). Now [retriggered](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openrtm_aist_core/3/).

**Comment by 130s** [comment]
[Aborted again](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openrtm_aist_core/3/console) for some reasons. Maybe [this is related](http://lists.ros.org/pipermail/ros-release/2014-April/004393.html) and if so I hope [next trial](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openrtm_aist_core/4/) thrives in.

**Comment by k-okada** [comment]
it seems http://jenkins.ros.org/ is so crowded and could not process
incoming jobs. I found that they restarted jenkins server several time over
last few days but did not fixed the problem.

**Comment by 130s** [comment]
Pre-release [aborted for third time](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openrtm_aist_core/4/console). Just one more try before making another action

**Comment by 130s** [comment]
Pre-release test [failed](http://jenkins.ros.org/job/prerelease-hydro-openrtm_aist_core/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=prerelease/5/consoleFull) but only at its downstream build. Seems like a good to go.

@k-okada Was there any discussion recently with ROS core team about numbering version? Do they agree that we only increment build version for some of our packages?

**Comment by 130s** [comment]
Done with https://github.com/ros/rosdistro/pull/3822 into hydro.

**Comment by 130s** [comment]
[Got a comment as expected](https://github.com/ros/rosdistro/pull/3822#issuecomment-40162669).

**Comment by 130s** [comment]
done
